.github/workflows/CompatHelper.yml
.github/workflows/TagBot.yml
.github/workflows/run_tests.yml

Adding actions, tag bot, compatibility helper

Add Github Actions 

---

test/ps_inverse.jl

this is a more robust version of the test that ensures we do not run into a case where `Base.inv` of a constant term is 0

add check for zero const term in inv test

---

Project.toml
src/local_identifiability.jl

Fix loc id check

---

Project.toml
src/util.jl

Multivariate factorization

---

docs/src/export/export.md
docs/src/index.md
docs/src/ioequations/ioequations.md
docs/src/tutorials/global_identifiability.md
src/StructuralIdentifiability.jl
src/global_identifiability.jl
src/pb_representation.jl

1. cleaning global identifiability tutorial, 2. adding differential reduction to the docs, 3. updating the link to the paper in the docs

Docs update

---

src/StructuralIdentifiability.jl
src/global_identifiability.jl
src/local_identifiability.jl
test/check_identifiability_from_ioeqs.jl
test/linear_compartment.jl
test/local_identifiability.jl
test/local_identifiability_me.jl
test/runtests.jl

Speeding up computation by specialising elements of a transcendence basis. Inspired by https://arxiv.org/abs/2204.01623

Specialising transcendence basis

---

src/util.jl

Replacing `R.base_ring` with `base_ring(R)`

fixing base_ring issue

---

examples/SIR_discrete.jl
src/ODE.jl
src/StructuralIdentifiability.jl
src/discrete.jl
src/primality_check.jl
src/util.jl
test/diff_sequence_solution.jl
test/local_identifiability_discrete.jl
test/local_identifiability_discrete_aux.jl
test/runtests.jl
test/sequence_solution.jl

Local identifiability for discrete-time systems

---

src/local_identifiability.jl
src/util.jl
test/mtk_compat.jl

Vector representation used in MTK input format

---

Project.toml

Adding all the combat updates together

updating compats for AA & Nemo

---

Project.toml

Making the lower bound for Julia to be 1.6

Lower bound for the Julia version (compat ne vinovat)

---

Project.toml

In order to make the registration happy

bounding julia version from above

---

ext/ModelingToolkitSIExt.jl
src/StructuralIdentifiability.jl
src/identifiable_functions.jl
src/known_ic.jl
test/extensions/modelingtoolkit.jl

This PR aims at addressing #324

Adding known_ic (known generic initial conditions) to the MTK interface

---

docs/src/assets/Project.toml
docs/src/tutorials/discrete_time.md
ext/ModelingToolkitSIExt.jl
test/extensions/modelingtoolkit.jl
test/local_identifiability_discrete.jl

Adding MTK interface for the discrete-time identifiability

---

.typos.toml
src/precompile.jl

Precompilation hangs on 1.11. This PR removes it.

removing precompilation

---

src/primality_check.jl
test/quotient_basis.jl

Adding zero-dim check to quotient_basis

---

src/RationalFunctionFields/IdealMQS.jl
test/RationalFunctionFields/raw_generators.jl

May be useful for Gleb. 
I did not see a speedup because I could not find models where GB is a bottleneck.
Do not merge. 
--Sasha

Let each numerator have its own denominator

---

src/lincomp.jl
test/linear_compartment.jl

Updating the interface of `linear_compartment_model` function to be a bit more intuitive and extending its docstring.

Lincomp revision

---

ext/ModelingToolkitSIExt.jl
test/extensions/modelingtoolkit.jl

Scalarizing MTK parameters

---

src/ODE.jl
src/StructuralIdentifiability.jl

An utility function to rename variables

Variable renaming
