SciML/StructuralIdentifiability.jl

docs/src/tutorials/global_identifiability.md

Hi! It seems most of the execution time in tutorial https://si.sciml.ai/dev/tutorials/global_identifiability/ is spent on compilation, so the comparison is not the most fair one. I suggest using `btime` there.
Moreover, it looks like assessing identifiability doesn't suffer much from probability increase. The following code
```julia
using Logging
global_logger(ConsoleLogger(stderr, Logging.Warn))
using BenchmarkTools
using StructuralIdentifiability
ode = @ODEmodel(
x'(t) = lm - d * x(t) - beta * x(t) * v(t),
y'(t) = beta * x(t) * v(t) - a * y(t),
v'(t) = k * y(t) - u * v(t),
w'(t) = c * x(t) * y(t) * w(t) - c * q * y(t) * w(t) - b * w(t),
z'(t) = c * q * y(t) * w(t) - h * z(t),
y1(t) = w(t),
y2(t) = z(t)
)
@btime global_id = assess_identifiability(ode, 0.99)
@btime global_id = …
```

use btime and rethink example in tutorial 😸 

---

src/ODE.jl
src/StructuralIdentifiability.jl
src/local_identifiability.jl
test/identifiability.jl
test/local_identifiability.jl
test/local_identifiability_me.jl
test/mtk_compat.jl

I think it would be good to keep `assess_local_identifiability` output format same as `assess_identifiability` (or at least similar, since the values are `Bool`s)

Create more verbose output for local identifiability

---

Project.toml
src/ODE.jl
src/util.jl
test/mtk_compat.jl

Was preventing from running examples like below:
```julia
using StructuralIdentifiability, ModelingToolkit
@parameters k1 k2 eB
@variables t xA(t) xB(t) xC(t) eA(t) eC(t) y1(t) y2(t) y3(t) y4(t)
D = Differential(t)
eqs = [
D(xA) ~ -k1 * xA,
D(xB) ~ k1 * xA - k2 * xB,
D(xC) ~ k2 * xB,
D(eA) ~ 0,
D(eC) ~ 0,
]
measured_quantities = [
y1 ~ xC,
y2 ~ eA * xA + eB * xB + eC * xC,
y3 ~ eA,
y4 ~ eC
]
@named ode = ODESystem(eqs, t)
result = assess_identifiability(ode, measured_quantities=measured_quantities)
```

Fix a bug in PreprocessODE

---

.github/workflows/run_tests.yml
Project.toml
benchmarking/benchmark_result.md
docs/src/tutorials/global_identifiability.md
docs/src/utils/global_identifiability.md
src/ODE.jl
test/mtk_compat.jl

Replacing `GroebnerBasis.jl` and `Singular.jl` with `Groebner.jl`. This resolves issues with Windows, non-ascii characters, and bugs with integer overflow.

Switch to groebner

---

.github/workflows/CompatHelper.yml

CompatHelper has been failing recently, this pr increases the action to v3 (see [here](https://github.com/JuliaRegistries/CompatHelper.jl/blob/d5dc1f4179ab17499619a2d920d07fc3bab353fb/.github/workflows/CompatHelper.yml#L29)).

Compat Helper v3

---

src/elimination.jl
src/global_identifiability.jl
src/io_equation.jl
src/primality_check.jl
test/io_projections.jl
test/runtests.jl

New approach for computing an extra projection: instead of using only input-projection for elimination (and running into large factorization), we now pass the random projection as input to the original elimination algorithm (so, elimination is being performed twice, c'est la vie) and its minimal equation is being computed along with the IO-projections from the original system.
The PR is aimed as fixing https://github.com/SciML/StructuralIdentifiability.jl/issues/132

Avoid factoring

---

src/ODE.jl
test/local_identifiability_discrete.jl
test/mtk_compat.jl

Allowing `assess_identifiability(de; measured_quantities = [x0])` in addition to previously used `assess_identifiability(de; measured_quantities = [y1 ~ x0])`

Allowing not to give names to the output functions in the MTK format

---

benchmarking/IdentifiableFunctions/results/cholera/logs_with_states
benchmarking/IdentifiableFunctions/results/generalizedLoktaVolterra (1o)/logs_with_states
benchmarking/IdentifiableFunctions/results/generalizedLoktaVolterra (2o)/logs_with_states
benchmarking/IdentifiableFunctions/results/p53/logs_with_states
src/RationalFunctionFields/IdealMQS.jl
src/RationalFunctionFields/RationalFunctionField.jl
src/RationalFunctionFields/normalforms.jl
src/util.jl

Abstract the saturation variable index

---

src/RationalFunctionFields/RationalFunctionField.jl
src/RationalFunctionFields/normalforms.jl
src/global_identifiability.jl

Currently:
```julia
StructuralIdentifiability.assess_identifiability(ode)
[ Info: Assessing local identifiability
[ Info: Local identifiability assessed in 5.2702728 seconds
[ Info: Assessing global identifiability
[ Info: Note: the input model has nontrivial submodels. If the computation for the full model will be too heavy, you may want to try to first analyze one of the submodels. They can be produced using function find_submodels
[ Info: Functions to check involve states
[ Info: Computing IO-equations
┌ Info: Computed in 6.4942927 seconds
│   :ioeq_time = :ioeq_time
└   ioeq_time = 6.4942927
[ Info: Computing Wronskians
┌ Info: Computed in 2.5463854 seconds
│   :wrnsk_time = :wrnsk_time
└   wrnsk_time = 2.5463854
[ Info: Dimensions of the Wronskians [2]
┌ Info: Ranks of the Wronskians …
```

Being more concise in logging

---

src/ODE.jl
src/StructuralIdentifiability.jl
src/discrete.jl
src/identifiable_functions.jl
src/local_identifiability.jl

The old name is kept but shows a warning. Addressing #239

Renaming `preprocess_ode` to `mtk_to_si`

---

docs/src/tutorials/discrete_time.md
docs/src/tutorials/identifiability.md
src/RationalFunctionFields/RationalFunctionField.jl
src/StructuralIdentifiability.jl
src/discrete.jl
src/global_identifiability.jl
src/identifiable_functions.jl
src/local_identifiability.jl
src/parametrizations.jl
test/local_identifiability_me.jl
test/mtk_compat.jl

renaming `p` to `prob_threschold`

---

.github/workflows/CI.yml
Project.toml
docs/src/tutorials/creating_ode.md
docs/src/tutorials/discrete_time.md
ext/ModelingToolkitSIExt.jl
src/StructuralIdentifiability.jl
test/extensions/modelingtoolkit.jl
test/runtests.jl

This is an attempt to fix the modelling toolkit extension, and reintroduce support for the `mtk_to_si` function, which was removed in the last update.
Changes:
- `mtk_to_si` is no longer exported from the extension. But instead created in the main package (without methods) and methods then added in the extension.
- I have removed the `export` statements in the extension as these should not be there.
- I have renamed the extension to `ModelingToolkitSIExt`. Motivation: extensions should (ideally) have names unique to both packages involved. If two packages both created extensions called `ModelingToolkitExt` (no unthinkable), these will overwrite each other, causing errors if loaded simultaneously.
Unfortunately this does not work fully. This code:
```julia
using StructuralIdentifiability, …
```

Fix ModelingTookit extension

---

src/ODE.jl
src/discrete.jl
src/util.jl
test/ode.jl

To handle systems like this:
```julia
using StructuralIdentifiability
ode = @ODEmodel(
🐁'(t) = a * 🐁 - b * 🐁 * 🦉,
🦉'(t) = c * 🦉 + d * 🐁 * 🦉,
y(t) = 🐁
)
```

Fix issues with unicode names

---

benchmarking/IdentifiableFunctions/experiments.jl
benchmarking/IdentifiableFunctions/homogenization.jl
src/io_equation.jl
src/parametrizations.jl
src/util.jl
test/paradigm_shift.jl

Alexey Ovchinnikov has reported the failure of an assertion during reparametrization on
```julia
ode = @ODEmodel(
x'(t) = b * (x(t)^2 + 1) / (2 * a),
y(t) = 2 * x(t) / (b * (1 + x(t)^2))
)
```
The problem was with computing the expressions of rational function wrt the tag variables, it is fixed.

Expression of a function in terms of generators of rational function field (bug fix)

---

.github/workflows/CI.yml
.github/workflows/Documentation.yml
.github/workflows/Downgrade.yml
.github/workflows/Invalidations.yml
Project.toml

Current PR makes `StructuralIdentifiability` incompatible with Julia version `1.10.3` (because of a [bug](https://github.com/JuliaLang/julia/issues/54356)) and excludes the version `1.10.3` from CI.

Restrict Julia version to <= 1.10.2

---

docs/src/tutorials/reparametrization.md
src/RationalFunctionFields/RationalFunctionField.jl
src/RationalFunctionFields/rankings.jl
src/global_identifiability.jl
src/identifiable_functions.jl
test/RationalFunctionFields/rational_function_cmp.jl
test/identifiable_functions.jl
test/runtests.jl

Monomial ordering used in MQS computation and the way the fractions are sorted in beautification are updated to arrive at more interpretable identifiable functions better suited for reparametrization.

Updating the ordering used in MQS computation

---

docs/src/tutorials/discrete_time.md
docs/src/tutorials/identifiability.md
docs/src/tutorials/reparametrization.md
src/power_series_utils.jl
src/util.jl
src/wronskian.jl

* Make previously math-styled entities math-styled
* Use code-style where entities should be code-styled
* Fix a typo p -> `poly`

doc: make font style coherent

---

.github/dependabot.yml

Currently, dependabot PRs primarily only update the patch and minor versions of the crates package for checking typos. Restrict this to only major version updates.

ci(dependabot): open dependabot PRs only for major versions

---

src/wronskian.jl

Fix for #421 , the sampling range was unnecessarily restrictive

fixing the random point generation in the wronskian computation

---

src/RationalFunctionFields/RationalFunctionField.jl
test/RationalFunctionFields/simplification.jl
test/identifiable_functions.jl
test/runtests.jl

Gives better simplification, e.g., for SLIQR

retaining original generators for the final casting
